---
- hosts: localhost
  vars_prompt:
    - name: vault_password
      prompt: "Enter Ansible Vault password"
      private: yes
    - name: sudo_password
      prompt: "Enter sudo password"
      private: yes
  vars:
    ansible_become_pass: "{{ sudo_password }}"
    user: "{{ ansible_env.USER }}"
    github_host_key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
  tasks:
    - name: Install packages
      become: yes
      apt:
        name:
          - i3
          - openssh-server
          - stow
          - git
          - neovim
          - zsh
        state: present

    - name: Start ssh service
      become: yes
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Create .ssh directory
      become: yes
      file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"

    - name: Copy encrypted ssh keys
      shell: "cat encrypted/ssh/id_ed25519 > /home/{{ user }}/.ssh/id_ed25519"
        
    - name: Create temporary vault password file
      copy:
        content: "{{ vault_password }}"
        dest: /tmp/vault_pass.txt
        mode: "0600"

    - name: Decrypt the private key
      shell: "ansible-vault decrypt /home/{{ user }}/.ssh/id_ed25519 --vault-password-file=/tmp/vault_pass.txt"
      register: decrypt_result

    - name: Remove the vault password file
      shell: "rm /tmp/vault_pass.txt"

    - name: Copy public ssh key
      copy:
        src: "public/ssh/id_ed25519.pub"
        dest: "/home/{{ user }}/.ssh/id_ed25519.pub"

    - name: Add GitHub to known_hosts
      known_hosts:
        path: "/home/{{ user }}/.ssh/known_hosts"
        name: "github.com"
        key: "{{ github_host_key }}"
      become: yes
      become_user: "{{ user }}"

    - name: Clone dotfiles repository
      git:
        repo: "git@github.com:1337jazz/dotfiles.git"
        dest: "/home/{{ user }}/dotfiles"

    - name: Stow dotfiles
      shell: "cd /home/{{ user }}/dotfiles && stow ."

    - name: Set zsh as default shell
      become: yes
      shell: "chsh -s $(which zsh)"

    - name: Install oh-my-zsh
      become: yes
      shell: sh -c "$(curl -fsSL https://install.ohmyz.sh/)"
      when: not (ansible_user_dir | search('oh-my-zsh'))
      tags: test
