---
- hosts: localhost
  become: yes
  tasks:
    - name: Install packages
      become: yes
      apt:
        name:
          - i3
          - openssh-server
          - stow
          - git
          - neovim
          - zsh
        state: present

    - name: Start ssh service
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Create .ssh directory
      file:
        path: "/home/{{ ansible.env.USER }}"
        state: directory
        mode: "0600"

    - name: Copy encrypted ssh keys
      copy:
        src: "encrypted/ssh/id_ed25519"
        dest: "/home/{{ ansible.env.USER }}/.ssh/id_ed25519"
        vars_prompt:
          - name: vault_password
            prompt: "Enter Ansible Vault password"
            private: yes

    - name: Decrypt the private key
      shell: "ansible-vault decrypt /home/{{ ansible.env.USER }}/.ssh/id_ed25519 --vault-password-file=/tmp/vault_pass.txt"
      vars:
        vault_pass_file: "/tmp/vault_pass.txt"
      environment:
        VAULT_PASSWORD_FILE: "{{ vault_pass_file }}"
      register: decrypt_result
      no_log: true

    - name: Remove the vault password file
      file:
        path: "{{ vault_pass_file }}"
        state: absent
      when: decrypt_result is succeeded

    - name: Copy public ssh key
      copy:
        src: "public/ssh/id_ed25519.pub"
        dest: "/home/{{ ansible.env.USER }}/.ssh/id_ed25519.pub"
